import type { ProfileKey } from '../profile.schema';

// IMPLEMENTATION.md §11.3 — each key → list of lowercased substrings that indicate it.
export const SYNONYMS: Partial<Record<ProfileKey, string[]>> = {
  'personal.firstName': [
    'first name',
    'given name',
    'fname',
    'firstname',
    'legal first',
    'forename',
    'first / given name',
  ],
  'personal.lastName': [
    'last name',
    'surname',
    'lname',
    'lastname',
    'legal last',
    'family name',
    'last / family name',
  ],
  'personal.middleName': ['middle name', 'middle initial', 'mname'],
  'personal.preferredName': [
    'preferred name',
    'nickname',
    'goes by',
    'preferred first',
    'known as',
  ],
  'personal.email': ['email', 'e-mail', 'email address', 'e mail'],
  'personal.phone': [
    'phone',
    'mobile',
    'telephone',
    'cell',
    'contact number',
    'phone number',
    'mobile number',
    'daytime phone',
  ],
  'personal.address.line1': [
    'address',
    'street address',
    'address line 1',
    'addr',
    'street',
    'mailing address',
    'current address',
    'residential address',
  ],
  'personal.address.line2': ['address line 2', 'apt', 'suite', 'unit', 'apartment'],
  'personal.address.city': ['city', 'town', 'municipality', 'city/town'],
  'personal.address.state': ['state', 'province', 'region', 'state/province', 'county'],
  'personal.address.zip': ['zip', 'postal code', 'postcode', 'zip code', 'pincode', 'pin code'],
  'personal.address.country': ['country', 'country/region', 'nation'],
  'links.linkedin': ['linkedin'],
  'links.github': ['github', 'git hub'],
  'links.portfolio': ['portfolio', 'behance', 'dribbble'],
  // NOTE: bare 'url' removed — it over-matched fields like Lever's urls[LinkedIn].
  // The autocomplete attribute 'url' still maps to website via AUTOCOMPLETE_MAP.
  'links.website': ['website', 'personal site', 'web site', 'personal website', 'blog'],
  'workAuth.authorizedToWork': [
    'authorized to work',
    'legally authorized',
    'work authorization',
    'eligible to work',
    'right to work',
    'work permit',
    'authorised to work',
  ],
  'workAuth.needsSponsorship': [
    'sponsorship',
    'require sponsorship',
    'visa sponsorship',
    'now or in the future require',
    'need sponsorship',
  ],
  'workAuth.requiresVisa': ['require a visa', 'visa status', 'visa required'],
  'eeo.gender': ['gender', 'sex'],
  'eeo.race': ['race', 'ethnicity'],
  'eeo.hispanicLatino': ['hispanic', 'latino'],
  'eeo.veteranStatus': ['veteran', 'protected veteran', 'military'],
  'eeo.disabilityStatus': ['disability', 'disabled'],
  'documents.resume': [
    'resume',
    'résumé',
    'cv',
    'curriculum vitae',
    'upload resume',
    'attach resume',
    'attach cv',
  ],
  'documents.coverLetter': ['cover letter', 'covering letter', 'motivation letter'],
  skills: ['skills', 'key skills', 'technical skills', 'core skills'],
};

// autocomplete attribute values map directly and are high-confidence.
export const AUTOCOMPLETE_MAP: Record<string, ProfileKey> = {
  'given-name': 'personal.firstName',
  'additional-name': 'personal.middleName',
  'family-name': 'personal.lastName',
  email: 'personal.email',
  tel: 'personal.phone',
  'address-line1': 'personal.address.line1',
  'address-line2': 'personal.address.line2',
  'address-level2': 'personal.address.city',
  'address-level1': 'personal.address.state',
  'postal-code': 'personal.address.zip',
  'country-name': 'personal.address.country',
  url: 'links.website',
};
