import type { ProfileKey } from '../profile.schema';

// IMPLEMENTATION.md §11.3 — each key → list of lowercased substrings that indicate it.
// Comprehensive dictionary covering Greenhouse, Workday, Lever, Indeed, SmartRecruiters,
// Ashby, iCIMS, JazzHR, Workable, Oracle, SuccessFactors, and generic career sites.
export const SYNONYMS: Partial<Record<ProfileKey, string[]>> = {
  'personal.firstName': [
    'first name',
    'given name',
    'fname',
    'firstname',
    'legal first',
    'forename',
    'first / given name',
    'candidate first name',
    'applicant first name',
    'your first name',
  ],
  'personal.lastName': [
    'last name',
    'surname',
    'lname',
    'lastname',
    'legal last',
    'family name',
    'last / family name',
    'candidate last name',
    'applicant last name',
    'your last name',
  ],
  'personal.middleName': ['middle name', 'middle initial', 'mname', 'middle'],
  'personal.preferredName': [
    'preferred name',
    'nickname',
    'goes by',
    'preferred first',
    'known as',
    'display name',
  ],
  'personal.email': [
    'email',
    'e-mail',
    'email address',
    'e mail',
    'your email',
    'contact email',
    'personal email',
    'work email',
  ],
  'personal.phone': [
    'phone',
    'mobile',
    'telephone',
    'cell',
    'contact number',
    'phone number',
    'mobile number',
    'daytime phone',
    'cell phone',
    'home phone',
    'work phone',
    'primary phone',
    'contact phone',
    'your phone',
    'mobile phone',
    'tel number',
  ],
  'personal.address.line1': [
    'address',
    'street address',
    'address line 1',
    'addr',
    'street',
    'mailing address',
    'current address',
    'residential address',
    'home address',
    'address 1',
    'street line 1',
  ],
  'personal.address.line2': [
    'address line 2',
    'apt',
    'suite',
    'unit',
    'apartment',
    'floor',
    'building',
    'address 2',
  ],
  'personal.address.city': [
    'city',
    'town',
    'municipality',
    'city/town',
    'current city',
    'home city',
  ],
  'personal.address.state': [
    'state',
    'province',
    'region',
    'state/province',
    'county',
    'state/region',
    'territory',
  ],
  'personal.address.zip': [
    'zip',
    'postal code',
    'postcode',
    'zip code',
    'pincode',
    'pin code',
    'zip/postal',
    'postal',
  ],
  'personal.address.country': [
    'country',
    'country/region',
    'nation',
    'country of residence',
    'home country',
  ],
  'links.linkedin': [
    'linkedin',
    'linkedin profile',
    'linkedin url',
    'linkedin link',
    'your linkedin',
  ],
  'links.github': [
    'github',
    'git hub',
    'github profile',
    'github url',
    'github link',
    'your github',
  ],
  'links.portfolio': [
    'portfolio',
    'behance',
    'dribbble',
    'portfolio url',
    'portfolio link',
    'work samples',
    'portfolio website',
  ],
  // NOTE: bare 'url' removed — it over-matched fields like Lever's urls[LinkedIn].
  'links.website': [
    'website',
    'personal site',
    'web site',
    'personal website',
    'blog',
    'personal url',
    'your website',
    'home page',
    'other url',
  ],
  'workAuth.authorizedToWork': [
    'authorized to work',
    'legally authorized',
    'work authorization',
    'eligible to work',
    'right to work',
    'work permit',
    'authorised to work',
    'legally eligible',
    'authorization to work',
    'legal right to work',
    'legally entitled to work',
    'permission to work',
    'able to document your u.s. citizenship',
    'prove your legal right',
  ],
  'workAuth.needsSponsorship': [
    'sponsorship',
    'require sponsorship',
    'visa sponsorship',
    'now or in the future require',
    'need sponsorship',
    'will you in the future need sponsorship',
    'need sponsorship from an employer',
    'obtain extend or renew',
    'immigration sponsorship',
    'employment sponsorship',
    'work visa sponsorship',
    'immigration status',
    'require work visa',
    'sponsor your employment',
    'employer sponsorship',
  ],
  'workAuth.requiresVisa': [
    'require a visa',
    'visa status',
    'visa required',
    'visa type',
    'current visa',
    'immigration visa',
    'work visa',
  ],
  'salary.expected': [
    'salary',
    'salary expectation',
    'expected salary',
    'desired salary',
    'salary requirement',
    'compensation',
    'expected compensation',
    'pay expectation',
    'annual salary',
    'salary per year',
    'total compensation',
    'current salary',
    'desired pay',
    'ctc',
    'expected ctc',
    'target salary',
    'salary range',
    'minimum salary',
    'pay rate',
    'hourly rate',
    'annual compensation',
  ],
  'eeo.gender': [
    'gender',
    'sex',
    'gender identity',
    'what is your gender',
    'how do you identify',
  ],
  'eeo.race': [
    'race',
    'ethnicity',
    'racial',
    'ethnic background',
    'race/ethnicity',
    'race ethnicity',
  ],
  'eeo.hispanicLatino': [
    'hispanic',
    'latino',
    'hispanic or latino',
    'hispanic/latino',
    'latinx',
  ],
  'eeo.veteranStatus': [
    'veteran',
    'protected veteran',
    'military',
    'veteran status',
    'military service',
    'armed forces',
    'military veteran',
  ],
  'eeo.disabilityStatus': [
    'disability',
    'disabled',
    'disability status',
    'handicap',
    'physical or mental disability',
    'reasonable accommodation',
  ],
  'documents.resume': [
    'resume',
    'cv',
    'curriculum vitae',
    'upload resume',
    'attach resume',
    'attach cv',
    'upload cv',
    'your resume',
    'upload your resume',
    'resume/cv',
  ],
  'documents.coverLetter': [
    'cover letter',
    'covering letter',
    'motivation letter',
    'letter of motivation',
    'upload cover letter',
    'attach cover letter',
  ],
  skills: [
    'skills',
    'key skills',
    'technical skills',
    'core skills',
    'relevant skills',
    'your skills',
    'expertise',
    'competencies',
    'proficiencies',
    'technologies',
    'programming languages',
    'tech stack',
  ],
  // Common free-text questions that should route to answer bank / LLM.
  // These map to 'freeText' so the side panel shows "Draft with AI" for them.
  freeText: [
    'how did you hear',
    'where did you hear',
    'referral source',
    'source of application',
    'how did you find',
    'why do you want to work',
    'why are you interested',
    'tell us about yourself',
    'cover letter',
    'additional information',
    'anything else',
    'comments',
    'message to hiring',
    'years of experience',
    'total experience',
    'notice period',
    'earliest start date',
    'when can you start',
    'available start date',
    'availability',
    'willing to relocate',
    'open to relocation',
    'current location',
    'preferred location',
    'why should we hire',
    'what makes you a good fit',
    'describe your experience',
    'criminal background',
    'background check',
    'non compete',
    'non-compete',
    'have you previously applied',
    'have you worked here before',
    'do you know anyone',
    'employee referral',
    'referred by',
  ],
};

// autocomplete attribute values map directly and are high-confidence.
export const AUTOCOMPLETE_MAP: Record<string, ProfileKey> = {
  'given-name': 'personal.firstName',
  'additional-name': 'personal.middleName',
  'family-name': 'personal.lastName',
  name: 'personal.firstName', // full name — handled by the composedValue hook
  'honorific-prefix': 'personal.preferredName',
  email: 'personal.email',
  tel: 'personal.phone',
  'tel-national': 'personal.phone',
  'tel-local': 'personal.phone',
  'address-line1': 'personal.address.line1',
  'street-address': 'personal.address.line1',
  'address-line2': 'personal.address.line2',
  'address-level2': 'personal.address.city',
  'address-level1': 'personal.address.state',
  'postal-code': 'personal.address.zip',
  'country-name': 'personal.address.country',
  country: 'personal.address.country',
  url: 'links.website',
  organization: 'experience', // current company
};
